@startuml
class Пользователь {
  + имя : String
  + email : String
}

class Сотрудник {
  + должность : String
}

class Меню {
  + дата : Date
  + тип_кухни : String
}

class Блюдо {
  + название : String
  + цена : Float
}

class Заказ {
  + дата : Date
  + статус : String
}

Пользователь <|-- Сотрудник
Сотрудник "1" --> "1..*" Меню : выбирает
Меню "1" --> "*" Блюдо : содержит
Пользователь "1" --> "*" Заказ : делает
Заказ "1" --> "*" Блюдо : включает
@enduml
